name: doctor_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.9
  scoped_model: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0
  page_transition: ^1.1.5
  pin_code_fields: ^2.3.0+3
  menu_button: '0.1.0+1'
  flutter_svg: ^0.19.1
  smooth_star_rating: ^1.0.4+2
  percent_indicator: ^2.1.1+1
  icofont_flutter: ^1.3.0
  dotted_border: ^1.0.5
  flutter_cupertino_date_picker: ^1.0.12
  image_picker: ^0.6.3+4
  file_picker: ^1.5.0+2
  table_calendar: '2.2.2' #custom edited
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  shared_preferences: ^0.5.6+3
  connectivityswift: ^1.1.1+4

  geolocator: ^5.1.5
  permission_handler: ^4.4.0+hotfix.2
  provider: ^4.0.1
  provider_architecture: ^1.0.6
  transparent_image: ^1.0.0
  basic_utils:
  printing: ^3.3.0
  path_provider: ^1.6.5
  onesignal_flutter: ^2.4.0
  pusher_websocket_flutter: ^0.2.0
  shimmer: ^1.1.1
  just_audio: ^0.1.8
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1
  flutter_spinkit: ^4.1.2
  flutter_cache_manager: ^1.3.0
  cached_network_image: ^2.2.0+1
  get_it: ^4.0.2
  flushbar: ^1.9.0
  url_launcher: ^5.7.10
  # url_launcher: ^5.4.10
  flutter_ringtone_player: ^2.0.0
  photo_view: ^0.9.2
  flutter_launcher_icons: ^0.7.5

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/doctor_plus_white_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/document/
    - assets/locale/de.json
    - assets/locale/en.json
    - assets/locale/ur.json
    - assets/icons/avatar.png
    - assets/icons/Doctor_Logo_white.png
    - assets/icons/Map_1614.png
    - assets/icons/doctor_male.png
    - assets/icons/doctor_female.png
    - assets/icons/down_arrow.png
    - assets/icons/searchIcon.png
    - assets/icons/maternity.png
    - assets/icons/undraw_doctor_kw_5_l.png
    - assets/icons/blog.png
    - assets/icons/calendar.png
    - assets/icons/hospital.png
    - assets/icons/record.png
    - assets/icons/Mask_2.png
    - assets/icons/Mask_3.png
    - assets/icons/Mask_4.png
    - assets/icons/person2.png
    - assets/icons/Group 1793.png
    - assets/icons/Doctor-Logo.png
    - assets/icons/undraw_message_sent_1030.png
    - assets/icons/backarrow.png
    - assets/icons/phone.png
    - assets/icons/back.svg
    - assets/icons/like.svg
    - assets/icons/timer.svg
    - assets/icons/review.svg
    - assets/icons/pay.svg
    - assets/icons/information.svg
    - assets/icons/smile.svg
    - assets/icons/morning.svg
    - assets/icons/Bell icon.svg
    - assets/icons/afternoon.svg
    - assets/icons/rating.png
    - assets/icons/doctor.png
    - assets/icons/staff1.png
    - assets/icons/undraw_resume_folder_2_arse.png
    - assets/icons/done.png
    - assets/icons/filled_outline.png
    - assets/icons/undraw_booking_33fn.png
    - assets/icons/user.svg
    - assets/icons/doctor.svg
    - assets/icons/clock.svg
    - assets/icons/rx.svg
    - assets/icons/health_check.svg
    - assets/icons/folder.svg
    - assets/icons/Doctor Logo.svg
    - assets/icons/Menugreen.svg
    - assets/icons/edit.svg
    - assets/icons/Menu.svg
    - assets/icons/image.svg
    - assets/icons/file-alt.svg
    - assets/icons/ui-image.svg
    - assets/icons/Group 1642.svg
    - assets/icons/Group_1849.png
    - assets/icons/bookmark.svg
    - assets/icons/DoctorLogoWhite.svg
    - assets/icons/logo.svg
    - assets/icons/logoChange.svg
    - assets/icons/logoSplash.svg
    - assets/icons/frIcon.png
    - assets/icons/drPlus.png
    - assets/icons/enIcon.png
    - assets/icons/afhanflag.png
    - assets/icons/Group_1851.svg
    - assets/icons/camera.svg
    - assets/icons/mic.svg
    - assets/icons/new_Logo_white.svg
    - assets/new/bookappointment.svg
    - assets/new/bookappointment-off.svg
    - assets/new/medicalrecords.svg
    - assets/new/medicalrecords-off.svg
    - assets/new/myappointments.svg
    - assets/new/myappointments-off.svg
    - assets/icons/doctorNew.svg
    - assets/icons/filledoutlineNew.svg
    - assets/icons/ratingNew.svg
    - assets/icons/staffNew.svg
    - assets/icons/blogger-b.svg
    - assets/icons/account-logout.svg
    - assets/icons/awesome-language.svg
    - assets/icons/family.svg
    - assets/icons/map-doctor.svg
    - assets/icons/profileIcon.svg
    - assets/icons/mapMark.svg
    - assets/icons/maleIcon.png
    - assets/icons/femaleIcon.png
    - assets/icons/experience-5.png



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #   assets:
  #     - assets/icons/avatar.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: LatoBlack
      fonts:
        - asset: assets/fontFamily/Lato-Black.ttf
    - family: LatoBlackItalic
      fonts:
        - asset: assets/fontFamily/Lato-BlackItalic.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fontFamily/Lato-Bold.ttf
    - family: LatoBoldItalic
      fonts:
        - asset: assets/fontFamily/Lato-BoldItalic.ttf
    - family: LatoItalic
      fonts:
        - asset: assets/fontFamily/Lato-Italic.ttf
    - family: LatoLight
      fonts:
        - asset: assets/fontFamily/Lato-Light.ttf
    - family: LatoLightItalic
      fonts:
        - asset: assets/fontFamily/Lato-LightItalic.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fontFamily/Lato-Regular.ttf
    - family: Lato-Thin
      fonts:
        - asset: assets/fontFamily/Lato-Thin.ttf
    - family: LatoThinItalic
      fonts:
        - asset: assets/fontFamily/Lato-ThinItalic.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
